### ISSUE TITLE
Basic installation how to

### ISSUE THREAD

**Issue by rtraykoski** [AnalogJ/lodestone#30]
Hi Jason,
I like your project ans i try to install on my macbook pro.
Ok i have understand to use docker in folder project and run : docker-compose up
It create the container and run ok. But i haven't any file. I download your sample folder AnalogJ/lodestone-test-docs and put all in folder ./docs but i have no file when i run localhost:4000
And another thing, where i try to make a search, i write my search word but i can't click enter. 
But when I click on enter nothing happens.
Have you more information for all that, because i like to try completely the project.
Have a nice day.
Best Regards
Robert

**Comment by Erwyn** [comment]
Hello,

Same issue here, here is what I get in the logs:

```
fscrawler_1      | 10:30:54,829 DEBUG [f.p.e.c.f.FsParserAbstract] [/ter Lyon Grenoble 010719.pdf] can be indexed: [true]
fscrawler_1      | 10:30:54,829 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: /ter Lyon Grenoble 010719.pdf
fscrawler_1      | 10:30:54,829 DEBUG [f.p.e.c.f.FsParserAbstract]     - not modified: creation date 2019-07-01T04:46:46.100 , file date 2019-07-01T04:46:46.100, last scan date 2019-09-02T10:29:52.777
fscrawler_1      | 10:30:54,829 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed files in [/usr/share/fscrawler/data]...
fscrawler_1      | 10:30:54,829 TRACE [f.p.e.c.f.FsParserAbstract] Querying elasticsearch for files in dir [path.root:57a5a3aa8c78aaf1a9aee610d0f241]
fscrawler_1      | 10:30:54,836 TRACE [f.p.e.c.f.FsParserAbstract] Response [fr.pilato.elasticsearch.crawler.fs.client.ESSearchResponse@95f1135]
fscrawler_1      | 10:30:54,836 TRACE [f.p.e.c.f.FsParserAbstract] We found: []
fscrawler_1      | 10:30:54,836 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed directories in [/usr/share/fscrawler/data]...
fscrawler_1      | 10:30:54,842 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler is going to sleep for 1m

```

**Comment by AnalogJ** [comment]
Hey @rtraykoski @Erwyn 
Sorry for the delay responding to your questions, I was traveling for the long weekend. 

The current file system watcher has a couple issues with loading files that already exist.
Try running the following command to update the "modified date" on each file

```
find . -exec touch {} \;
```

Can you confirm that it fixed your issues?

**Comment by AnalogJ** [comment]
Also @rtraykoski you're going to need to put the documents inside the `watchfolder` directory, not `docs`

**Comment by Erwyn** [comment]
Fixes it indeed.

Thank you very much!
