### ISSUE TITLE
reverse proxy fscrawler missing port

### ISSUE THREAD

**Issue by RussellGrew** [AnalogJ/lodestone#36]
Hi,

Thanks for sharing this project. I have been looking for something like this.

When I spin up on Ubuntu 18.04 I see constant

```
reverse-proxy_1  | time="2019-11-02T02:33:48Z" level=error msg="port is missing" providerName=docker container=fscrawler-lodestone-d8525a5f5cdc3439c626c7757935b2f7b1aadff8c2a05cd5f04a07353031f627
```

And can't search for anything in the /web UI. The status dashboard suggests it has seen the documents I added to the watchfolder.

I tried removing `--api.insecure=true` for Traefik in the docker-compose.yml but it didn't solve anything.

Please let me know if I can assist with further logs.

Thanks.

**Comment by RussellGrew** [comment]
I managed to get it working. I had something else running on that port.

I may have had to chown the thumbnails folder, and then touch the contents of the watchfolder. I am not certain what solved it.

**Comment by AnalogJ** [comment]
touching the contents of the directory probably fixed the issue. The status dashboard is a placeholder ATM, it doesn't actually show the last updated date/time. 

I'm working on a new publisher/processor system in the https://github.com/AnalogJ/lodestone/tree/status_api branch, which will also do thumbnail generation and OCR.
