### ISSUE TITLE
Use Reverse Proxy already in environment

### ISSUE THREAD

**Issue by kennyparsons** [AnalogJ/lodestone#62]
Love the project, excited about getting it going. Only the big problem is that I already have a reverse proxy in my environment. I currently use Caddy as my reverse proxy. So it's not just as easy as removing the traefik container from the compose file. 

Can you help with the necessary components required to get this to work through an existing proxy?

**Comment by AnalogJ** [comment]
Ah, I already ran into this issue myself. Just for future users who search this issue, if you already have a traefik proxy running, you can re-use it using a modified [docker-compose.yml](https://github.com/mediadepot/templates/blob/master/stacks/lodestone/docker-compose.yml) file.

Onto your issue @kennyparsons, I haven't actually used caddy myself, but hopefully the following information is enough to help you get started:

There are only 2 containers that need to be routed via an external proxy:
- `webapp` needs to have the `/api/*` and `/web/*` paths routed to port `3000`
- `storage` needs to have the `/storage/*` path routed to port `9000`. However we need to strip the `/storage` prefix when sending the request to the container. 

In traefik rewriting the path is done via the `stripprefix` middleware, but I assume Caddy has a similar function. https://github.com/caddyserver/caddy/issues/2813 seems relevant

Does that help?

**Comment by LilTrublMakr** [comment]
Would it be possible to post a Traefik V1 compose file? I have a system already that uses V1 using a guide from SmartHomeBeginner. I tried to update it to V2 but it just borked EVERYTHING,

If it helps, here is a typical Traefik V1 block per container for me:

```
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=program'
      - 'traefik.docker.network=proxy'
      - 'traefik.frontend.rule=Host:program.${DOMAIN}'
      - 'traefik.port=8080'
      - 'traefik.frontend.entryPoints=https'
```

**Comment by AnalogJ** [comment]
Hey, actually the next beta won’t require a reverse proxy at all. If you want to test it out, you can build the images in the beta-2 branch, or wait a bit until the beta 2 branch gets merged into master and I announce beta2 on the mailing list/reddit. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LilTrublMakr** [comment]
I am a little confused because in the noproxy compose file, it specifically states that it still needs a proxy...

```
# This is a no-proxy docker-compose configuration for Lodestone.
# It will not work out of the box, since it requires you to provide your own reverse proxy.
# You can however use it as the basis of your own customized docker-compose/docker script.
```

**Comment by AnalogJ** [comment]
@LilTrublMakr  apologies, it seems that I didn't commit some of my local changes. 
The `beta2` branch has been updated. There's no longer a `noproxy` docker-compose file, instead you can use the normal `docker-compose.yml` file. I've completely stripped out the traefik service/container.
