### ISSUE TITLE
Dashboard page shows no files upon opening

### ISSUE THREAD

**Issue by LilTrublMakr** [AnalogJ/lodestone#85]
Severity (imo): Minor

Conditions: Single file type uploaded. In my case, 2 PDF files.

Expected behavior: When opening the dashboard with no search terms (foo.bar/web/dashboard), all uploaded files should appear under the search bar.

Steps to reproduce:
1. Uploaded 2 PDF files via FTP
2. Opened the dashboard URL
3. No files are shown until toggling the PDF toggle

Notes: I originally thought it was a bug that turning the toggle off, the PDF files would still be shown, but when I uploaded a different file type (png) and realized that all of the files are supposed to appear. This might be related to #61 but I am not entirely sure.

**Comment by AnalogJ** [comment]
Hey @LilTrublMakr 
Yeah, the issue you're seeing is tracked via #61. 
Basically the code to trigger the initial search is not being called automatically, I'm working on a fix.
