### ISSUE TITLE
Scan Storage time, subfolder tags

### ISSUE THREAD

**Issue by D3L05** [AnalogJ/lodestone#92]
Hi, every document that it put in data\storage\documents is not processed till I click sync in elastichsearch in status page

It would be possible to auto create tags based in subfolder in data\storage\documents??

thanks!

**Comment by AnalogJ** [comment]
Hey @D3L05 
Thats very unfortunate.  
Lodestone uses file system events to detect new documents and add them to the queue. Different file systems have different capabilities, and ntfs, exfs, fat32, etc are all slightly different. The docker client can also cause issues. 

Can you give me a bit more information about you system? What host os are you running? 
I'm working on a feature to enable a "polling" mode, which would work consistently across different file systems.

Lodestone will already add a tag for each subfolder in the path. eg.

- `data\storage\documents\tagname\doc.pdf` will add a tag of `tagname` to the document automatically. 
- `data\storage\documents\tag1\tag2\doc.pdf` will add *two* tags, `tag1` and `tag2` to the document automatically. 

I hope that answers all your questions!

**Comment by D3L05** [comment]
Hi, thanks for the information!

currently im testing with Win 10 v1809

**Comment by D3L05** [comment]
tried in win 10 1909 and it works like a charm, thanks!
