### ISSUE TITLE
Dockerhub for unRaid

### ISSUE THREAD

**Issue by bdillahu** [AnalogJ/lodestone#96]
As I understand it, things are working with unRaid now.

I could have sworn I saw this in Dockerhub at one point (unRaid is set to easily pull from Dockerhub), but not finding it now. Not sure how hard that is to set up an auto-build.

I will see about loading it manually, but thought I would suggest it.

**Comment by AnalogJ** [comment]
yep, the images are available in dockersign hub under analogj/lodestone.
Different components have different images however.

**Comment by bdillahu** [comment]
Got it... duh, sorry, user error I think...
